#include "constants.h"
const int SCREEN_WIDTH = 1280; /* px */
const int SCREEN_HEIGHT = 720; /* px */
const int FPS = 60; /* frames per second */
const int PADDING_LEFT = 50; /* px */
const int SPACING = 0;
const char *BACKGROUND_IMAGE_DIR = "D:/code/Repositories/raylib_project/assets/images/background.png";
const char *QUESTION_IMAGE_DIR = "D:/code/Repositories/raylib_project/assets/images/question.png";
const char *LEFT_ANSWER_IMAGE_DIR = "D:/code/Repositories/raylib_project/assets/images/answerleft.png";
const char *RIGHT_ANSWER_IMAGE_DIR = "D:/code/Repositories/raylib_project/assets/images/answerright.png";
const char *DEFAULT_FONT_DIR = "D:/code/Repositories/raylib_project/font/Nunito-Medium.ttf";
const char *A_ANSWER_DIR = "D:/code/Repositories/raylib_project/assets/images/answerA.png";
const char *A_ANSWER_SELECTED_DIR = "D:/code/Repositories/raylib_project/assets/images/answerA_selection.png";
const char *B_ANSWER_DIR = "D:/code/Repositories/raylib_project/assets/images/answerB.png";
const char *B_ANSWER_SELECTED_DIR = "D:/code/Repositories/raylib_project/assets/images/answerB_selection.png";
const char *C_ANSWER_DIR = "D:/code/Repositories/raylib_project/assets/images/answerC.png";
const char *C_ANSWER_SELECTED_DIR = "D:/code/Repositories/raylib_project/assets/images/answerC_selection.png";
const char *D_ANSWER_DIR = "D:/code/Repositories/raylib_project/assets/images/answerD.png";
const char *D_ANSWER_SELECTED_DIR = "D:/code/Repositories/raylib_project/assets/images/answerD_selection.png";
const Color TEXT_COLOR = WHITE;
const Color TRANSPARENT = (Color) {0, 0, 0, 0};
const char *TITLE_WINDOW_LOGIN = "Đăng nhập";
const char *TITLE_WINDOW_GAME = "Ai là triệu phú";
