#include "constants.h"

const int SCREEN_WIDTH = 1280; /* px */
const int SCREEN_HEIGHT = 720; /* px */
const int FPS = 60; /* frames per second */
const int PADDING_LEFT = 50; /* px */
const int SPACING = 0;
const char *START_BACKGROUND = "D:/code/repositories/raylib_project/assets/images/background.png";
const char *BACKGROUND_IMAGE = "D:/code/repositories/raylib_project/assets/images/bg.png";
const char *DATA = "D:/code/repositories/raylib_project/data.json";
const char *QUESTION_IMAGE = "D:/code/repositories/raylib_project/assets/images/question.png";
const char *DEFAULT_FONT = "D:/code/repositories/raylib_project/font/Nunito-Medium.ttf";
const char *ASSISTANCES = "D:/code/repositories/raylib_project/assets/images/assistances.png";
const char *FIFTY_FIFTY = "D:/code/repositories/raylib_project/assets/images/50-50.png";
const char *FIFTY_FIFTY_USED = "D:/code/repositories/raylib_project/assets/images/50-50_used.png";
const char *PLUS_ONE = "D:/code/repositories/raylib_project/assets/images/plus_one.png";
const char *PLUS_ONE_USED = "D:/code/repositories/raylib_project/assets/images/plus_one_used.png";
const char *ASK_EXPERT = "D:/code/repositories/raylib_project/assets/images/ask_expert.png";
const char *ASK_EXPERT_USED = "D:/code/repositories/raylib_project/assets/images/ask_expert_used.png";
const char *A_ANSWER = "D:/code/repositories/raylib_project/assets/images/answerA.png";
const char *A_ANSWER_SELECTED = "D:/code/repositories/raylib_project/assets/images/answerA_selection.png";
const char *A_RIGHT_ANSWER = "D:/code/repositories/raylib_project/assets/images/answerA_right.png";
const char *B_ANSWER = "D:/code/repositories/raylib_project/assets/images/answerB.png";
const char *B_ANSWER_SELECTED = "D:/code/repositories/raylib_project/assets/images/answerB_selection.png";
const char *B_RIGHT_ANSWER = "D:/code/repositories/raylib_project/assets/images/answerB_right.png";
const char *C_ANSWER_DIR = "D:/code/repositories/raylib_project/assets/images/answerC.png";
const char *C_ANSWER_SELECTED = "D:/code/repositories/raylib_project/assets/images/answerC_selection.png";
const char *C_RIGHT_ANSWER = "D:/code/repositories/raylib_project/assets/images/answerC_right.png";
const char *D_ANSWER_DIR = "D:/code/repositories/raylib_project/assets/images/answerD.png";
const char *D_ANSWER_SELECTED = "D:/code/repositories/raylib_project/assets/images/answerD_selection.png";
const char *D_RIGHT_ANSWER = "D:/code/repositories/raylib_project/assets/images/answerD_right.png";
const char *CURRENT_LEVEL_BG = "D:/code/repositories/raylib_project/assets/images/level.png";
const char *REWARDS_BG = "D:/code/repositories/raylib_project/assets/images/rewards.png";
const char *REWARD_BOARD = "D:/code/repositories/raylib_project/assets/images/reward_board.png";
const char *REWARD_BOX = "D:/code/repositories/raylib_project/assets/images/reward_box.png";
const char *LOGO = "D:/code/repositories/raylib_project/assets/images/logo.png";
const char *START_BUTTON = "D:/code/repositories/raylib_project/assets/images/start_img.png";
const Color TEXT_COLOR = WHITE;
const char *CORRECT_ANSWER_SOUND = "D:/code/repositories/raylib_project/assets/audio/correct_answer.mp3";
const char *WRONG_ANSWER_SOUND = "D:/code/repositories/raylib_project/assets/audio/wrong_answer.mp3";
const char *START_SOUND = "D:/code/repositories/raylib_project/assets/audio/start_sound.mp3";
const Color TRANSPARENT = (Color) {0, 0, 0, 0};
const char *TITLE_WINDOW_GAME = "Ai là triệu phú";
