#include "constants.h"
const int SCREEN_WIDTH = 1280; /* px */
const int SCREEN_HEIGHT = 720; /* px */
const int FPS = 60; /* frames per second */
const int PADDING_LEFT = 50; /* px */
const int SPACING = 0;
const char *START_BACKGROUND = "D:/code/Repositories/raylib_project/assets/images/background.png";
const char *BACKGROUND_IMAGE = "D:/code/Repositories/raylib_project/assets/images/bg.png";
const char *QUESTION_IMAGE = "D:/code/Repositories/raylib_project/assets/images/question.png";
const char *DEFAULT_FONT = "D:/code/Repositories/raylib_project/font/Nunito-Medium.ttf";
const char *A_ANSWER = "D:/code/Repositories/raylib_project/assets/images/answerA.png";
const char *A_ANSWER_SELECTED = "D:/code/Repositories/raylib_project/assets/images/answerA_selection.png";
const char *A_RIGHT_ANSWER = "D:/code/Repositories/raylib_project/assets/images/answerA_right.png";
const char *B_ANSWER = "D:/code/Repositories/raylib_project/assets/images/answerB.png";
const char *B_ANSWER_SELECTED = "D:/code/Repositories/raylib_project/assets/images/answerB_selection.png";
const char *B_RIGHT_ANSWER = "D:/code/Repositories/raylib_project/assets/images/answerB_right.png";
const char *C_ANSWER_DIR = "D:/code/Repositories/raylib_project/assets/images/answerC.png";
const char *C_ANSWER_SELECTED = "D:/code/Repositories/raylib_project/assets/images/answerC_selection.png";
const char *C_RIGHT_ANSWER = "D:/code/Repositories/raylib_project/assets/images/answerC_right.png";
const char *D_ANSWER_DIR = "D:/code/Repositories/raylib_project/assets/images/answerD.png";
const char *D_ANSWER_SELECTED = "D:/code/Repositories/raylib_project/assets/images/answerD_selection.png";
const char *D_RIGHT_ANSWER = "D:/code/Repositories/raylib_project/assets/images/answerD_right.png";
const char *CURRENT_LEVEL_BG = "D:/code/Repositories/raylib_project/assets/images/level.png";
const char *REWARDS_BG = "D:/code/Repositories/raylib_project/assets/images/rewards.png";
const char *REWARD_BOARD = "D:/code/Repositories/raylib_project/assets/images/reward_board.png";
const char *LOGO = "D:/code/Repositories/raylib_project/assets/images/logo.png";
const char *START_BUTTON = "D:/code/Repositories/raylib_project/assets/images/start_img.png";
const Color TEXT_COLOR = WHITE;
const Color TRANSPARENT = (Color) {0, 0, 0, 0};
const char *TITLE_WINDOW_GAME = "Ai là triệu phú";
